### ISSUE TITLE
flask koyeb

### ISSUE THREAD

**Issue by Aassauhi** [VJBots/VJ-Codes#1]
please prove code for deployable on koyeb
like
run cmd
app py
requirement 

it is deleted noe

**Comment by SudoR2spr** [comment]
> please prove code for deployable on koyeb like run cmd app py requirement
> 
> it is deleted noe

You watch the full video tutorial, everything is explained there

**Comment by SudoR2spr** [comment]
# run cmd.txt file .......

gunicorn app:app & python3 main.py
              or
gunicorn app:app & python3 bot.py

**Comment by Aassauhi** [comment]
![IMG_20240727_015103](https://github.com/user-attachments/assets/ebb98444-2906-4ddd-aaf6-90f05aec6dc9)


https://github.com/VJBots/VJ-Codes
please providd these 3 file.. 

it is not available in this repo vjcode repo

**Comment by Aassauhi** [comment]
thanks 😊
